### PR TITLE
merge development into main

### PR DESCRIPTION
**Pull request by axtloss**
this removes the crystal-extra repo from the pacman config

### CODE REVIEW

**Review by mchalunderscore — APPROVED** [review]

**Review by SomethingGeneric — APPROVED** [review]
Looks good to me!

**Comment by SomethingGeneric** [comment]
@not-my-segfault @axtloss gonna wait for y'all to merge tho in case we want more stuff before the next ci job?

**Comment by axtloss** [comment]
we still have to rebuild the new version of jade gui once that gets merged into main, then we could merge this

**Comment by SomethingGeneric** [comment]
See i knew there was a reason to wait for input

**Pull request merged**
